name: slice_test_env4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.2.0
  - torchaudio=2.5.0
  - pytorch-cuda=11.8
  - torchvision=0.20.0
  - pytorch=2.5.0
  - pip:
    - pytorch-lightning==2.4.0
    - tensorboard==2.17.1
    - tabulate>=0.9.0
    - tqdm>=4.66.5
    - pillow>=10.4.0
    - notebook>=7.2.2
    - jupyterlab>=4.2.5
    - matplotlib>=3.9.2
    - seaborn>=0.13.2
    - ipywidgets>=8.1.2
    - ipykernel==6.29.5
    - scikit-image==0.25.0
    - scikit-learn==1.6.0
    - rbo==0.1.3
    - scipy==1.15.0
    - joblib==1.4.2
    - pandas==2.2.3
    - opencv-python==4.10.0.84
    - pycocotools==2.0.8
    - pingouin==0.5.5